-- Add advanced batting stat columns to player_batting_stats
ALTER TABLE league.player_batting_stats
  ADD COLUMN IF NOT EXISTS qab         INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hhb         INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ld          INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fb          INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gb          INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS babip       NUMERIC(5,4),
  ADD COLUMN IF NOT EXISTS ba_risp     NUMERIC(5,4),
  ADD COLUMN IF NOT EXISTS lob         INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS two_out_rbi INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS xbh         INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tb          INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ps          INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ps_pa       NUMERIC(6,3),
  ADD COLUMN IF NOT EXISTS two_s3      INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS six_plus    INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gidp        INTEGER      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ci          INTEGER      NOT NULL DEFAULT 0;
